name: Rust Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Run ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [test, test-all, test-no-default]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ github.event.repository.name }}-cargo
          cache-on-failure: true
      - name: Run ${{ matrix.target }}
        run: make ${{ matrix.target }}

  wasm:
    name: Wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ github.event.repository.name }}-cargo
          cache-on-failure: true
      - name: Check WebAssembly target
        run: make check-wasm
