name: Test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Test (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [test, test-all, test-no-default]
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ github.event.repository.name }}-cargo
          cache-on-failure: true
      - run: make ${{ matrix.target }}

  wasm:
    name: Wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ github.event.repository.name }}-cargo
          cache-on-failure: true
      - run: make check-wasm
